name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: レポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Dart SDKをセットアップ
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: 依存関係をインストール
        run: dart pub get  # Dartの依存関係をインストール

      - name: テストを実行
        run: dart test  # Dartのテストを実行

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: レポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: アプリをデプロイ
        run: |
          echo "デプロイ処理をここに記述"
