name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: レポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Flutter SDKをセットアップ
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: 依存関係をインストール
        run: flutter pub get  # Flutterの依存関係をインストール

      - name: テストを実行
        run: flutter test  # Flutterのテストを実行

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: レポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: アプリをデプロイ
        run: |
          echo "デプロイ処理をここに記述"
