name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: レポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Flutter SDKをインストール
        run: |
          git clone https://github.com/flutter/flutter.git
          cd flutter
          git checkout stable
          echo "export PATH=\$PATH:`pwd`/bin" >> $GITHUB_ENV
          source $GITHUB_ENV
                    
      - name: Flutterの依存関係をインストール
        run: flutter pub get

      - name: テストを実行
        run: flutter test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: レポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: アプリをデプロイ
        run: |
          echo "デプロイ処理をここに記述"
