name: Flutter CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test:
    name: Build and Test Flutter App
    runs-on: macos-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Flutter をセットアップ
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Flutter パッケージの取得
        run: flutter pub get

      - name: Flutter の静的解析
        run: flutter analyze

      - name: Flutter のテスト実行
        run: flutter test

      - name: アプリのビルド (Android)
        run: flutter build apk --release

      - name: Build iOS App
      env:
        FASTLANE_MATCH_GIT_URL: "https://github.com/Sseafood/windSpace_members.git"
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          gem install fastlane
          fastlane match development
          flutter build ios --release
      
